apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-test
spec:
  replicas: 40
  selector:
    matchLabels:
      app: ca-test
  template:
    metadata:
      labels:
        app: ca-test
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            cpu: "3500m"
