apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::169020557702:role/eksctl-eks-learning-addon-iamserviceaccount-k-Role1-VkzAnVJ6s5WI
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"k8s-addon":"cluster-autoscaler.addons.k8s.io","k8s-app":"cluster-autoscaler"},"name":"cluster-autoscaler","namespace":"kube-system"}}
  creationTimestamp: "2025-12-04T11:33:07Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
  resourceVersion: "14752"
  uid: 09da3beb-5d66-4347-acdd-a48da4e7e711
